name: Test Automation Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test-suite:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [dev, staging, prod]
        browser: [chrome, firefox, edge]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    
    - name: Install Chrome Browser
      uses: browser-actions/setup-chrome@latest
    
    - name: Run Test Suite
      run: |
        mvn clean test -Denv=${{ matrix.environment }} -Dbrowser=${{ matrix.browser }}
      env:
        CI: true
        ENVIRONMENT: ${{ matrix.environment }}
    
    - name: Generate ExtentReports
      run: |
        mvn clean test -Dreporting.enabled=true
      if: always()
    
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports-${{ matrix.environment }}-${{ matrix.browser }}
        path: |
          target/surefire-reports/
          target/extent-reports/
          screenshots/
    
    - name: Notify Slack on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#qa-alerts'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}